### ISSUE TITLE
单击时消除动量

### ISSUE THREAD

**Issue by quank123wip** [itorr/sakana#32]
在网页端（```Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63```）用鼠标点击但不拖动运动中的对象再松开后，物体的动量并没有改变。建议在单击时重置物体的动量。

**Comment by itorr** [comment]
因为这个是弹簧，只有移动到弹簧无弹力的角度高度才应该是无动量

**Comment by itorr** [comment]
确实，现在单击时
```javascript
    v.w = 0;
    v.t = 0;
```
