### ISSUE TITLE
requestAnimationFrame是基于刷新率进行计算的，在刷新率高的显示器中速度过快异常。

### ISSUE THREAD

**Issue by AlishaHawkward** [itorr/sakana#39]
在60FPS，144FPS，240FPS下的速度表现明显不同，希望基于时间进行计算，或者使用setInterval(1000/60)来限定一下鬼畜速度。

**Comment by itorr** [comment]
在低于 40ms 帧间隔时智能调整 inertia 使速度近似一致，超出 40ms 的渲染速度时放任 RAF 自由
