### ISSUE TITLE
有关移动端无法正确显示约会模式的问题

### ISSUE THREAD

**Issue by Fros1er** [itorr/sakana#42]
`center-bottom div { margin: 0 -200px; }`，然后把千束往上放150px，泷奈往下放50px看起来不错
~~不过自己非常菜（指不会写less）所以就扔这了orz~~
![image](https://user-images.githubusercontent.com/34234343/187071505-a4e45e69-7e9d-4574-be9c-8a9fbd816335.png)

**Comment by itorr** [comment]
采用！不过现在的尺寸叠在一起会导致点击范围遮蔽，再缩小一点
