### ISSUE TITLE
为啥子编译出来没有人物模型呢

### ISSUE THREAD

**Issue by haoduck** [itorr/sakana#47]
![image](https://user-images.githubusercontent.com/56804964/187354814-9e4c06b3-2288-4b98-a8f6-afa83cea71f9.png)

直接引用sakana.js也是这样子，现在仓库上的[sakana.min.js](https://github.com/itorr/sakana/blob/3ad748aade5967c83c685bc005fcd6162457ad51/html/sakana.min.js)就正常

**Comment by itorr** [comment]
本地调试的话用 test.html 就好，还需要引用一个 sakana.css 文件，它需要用 sakana.less 生成。
如果编辑器是 VSCode 之类，建议安装个 less 转换插件

**Comment by haoduck** [comment]
> 本地调试的话用 test.html 就好，还需要引用一个 sakana.css 文件，它需要用 sakana.less 生成。 如果编辑器是 VSCode 之类，建议安装个 less 转换插件

原来如此，谢谢你
