### ISSUE TITLE
电脑端无声音

### ISSUE THREAD

**Issue by nkh0472** [itorr/sakana#49]
已关闭`静音`，不管怎么拖动人物/开启`自动`按钮均无声音播放。
同时：浏览器标签上未曾出现播放音频指示标识、网页右键查看源码中无mp3/m4a关键词出现、审查网页的载入资源中亦无音频文件。
尝试关闭所有浏览器插件/使用无插件的无痕浏览下启动网页也无效果，并且浏览器控制台没有错误提示信息。

环境：
<html>
<body>

Microsoft Edge | 105.0.1343.25 (正式版本) (64 位)
-- | --
修订 | d3a25e9da89eba5d55f1ab48fced0ccd321e4ba8
操作系统 | Windows 11 Version 22H2 (Build 22621.382)
JavaScript | V8 10.5.12.4
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.25

</body>
</html>

**Comment by nkh0472** [comment]
补充DevTools的网络标签页，可见无音频文件载入：
![image](https://user-images.githubusercontent.com/67589323/188301787-61ccc433-1f28-4d49-95a0-852a2588e5bc.png)

**Comment by nkh0472** [comment]
> 目前的触发规则有一点点严格 takina 横向右拖动 不上下位移松手应该就可以触发 chisato 纵向下拖动 不左右位移松手应该就可以触发

确实，按照这个方法可以触发了。
但还是要说严重影像用户体验（

**Comment by itorr** [comment]
> > 目前的触发规则有一点点严格 takina 横向右拖动 不上下位移松手应该就可以触发 chisato 纵向下拖动 不左右位移松手应该就可以触发
> 
> 确实，按照这个方法可以触发了。 但还是要说严重影像用户体验（

下个版本考虑放开一些触发判定😆
