### ISSUE TITLE
可以以npm的方式安装吗？

### ISSUE THREAD

**Issue by zhoufanglu** [itorr/sakana#55]
目前博客用的是vuepress， 好像支持支npm方式安装插件

**Comment by zhoufanglu** [comment]
> 可以的
> 
> ## npm install
> ```shell
> npm i sakana -d
> ```
> 
> ## 准备 DOM 结构
> ```
> <div class="sakana-box"></div>
> ```
> 
> ## 引入，启动
> ```js
> import Sakana from 'sakana';
> 
> Sakana.init({
>   el:         '.sakana-box',     // 启动元素 node 或 选择器
>   scale:      .5,                // 缩放倍数
>   canSwitchCharacter: true,      // 允许换角色
> });
> ```
> 
> 更多可以参考 [选项与方法](https://github.com/itorr/sakana/blob/main/README.md#%E9%80%89%E9%A1%B9%E4%B8%8E%E6%96%B9%E6%B3%95)

可以以plugin的形式创建吗？
![image](https://user-images.githubusercontent.com/24451091/200801581-f9ffa6d1-8f34-470c-83f5-5cf322f5a6a7.png)

**Comment by itorr** [comment]
> > ```js
> >  el:         '.sakana-box',     // 启动元素 node 或 选择器
> >   scale:      .5,                // 缩放倍数
> >   canSwitchCharacter: true,      // 允许换角色
> > ```
> 
> 试了下 好像不行 vuepress增加dom需要改源码吧？

我这里只需要启动之前有这个 DOM 元素即可，可以用 javascript DOM API 创建

我写个例子
```javascript
// 引入🐟
import Sakana from 'sakana';

// 创建 DOM
const el = document.createElement('div');

// 设定样式放置到右下角
el.style.cssText = `position: fixed;right: 0;bottom: 0;transform-origin: 100% 100%;`;

// 放到 body 里
document.body.appendChild(el);

// 启动，传入刚刚创建的 el DOM 元素
Sakana.init({
	el,
	scale: .5
});
```

**Comment by zhoufanglu** [comment]
> 

十分感谢 明白了 我试试

**Comment by zhoufanglu** [comment]
> > > ```js
> > >  el:         '.sakana-box',     // 启动元素 node 或 选择器
> > >   scale:      .5,                // 缩放倍数
> > >   canSwitchCharacter: true,      // 允许换角色
> > > ```
> > 
> > 
> > 试了下 好像不行 vuepress增加dom需要改源码吧？
> 
> 我这里只需要启动之前有这个 DOM 元素即可，可以用 javascript DOM API 创建
> 
> 我写个例子
> 
> ```js
> // 引入🐟
> import Sakana from 'sakana';
> 
> // 创建 DOM
> const el = document.createElement('div');
> 
> // 设定样式放置到右下角
> el.style.cssText = `position: fixed;right: 0;bottom: 0;transform-origin: 100% 100%;`;
> 
> // 放到 body 里
> document.body.appendChild(el);
> 
> // 启动，传入刚刚创建的 el DOM 元素
> Sakana.init({
> 	el,
> 	scale: .5
> });
> ```

这个源码里面用了document  , vuepress 打包直接报错了，有没有什么好的方案
![image](https://user-images.githubusercontent.com/24451091/201308977-c333d07b-a990-41fd-9927-8b08ec09ddff.png)

**Comment by zhoufanglu** [comment]
> ```js
> scale: .5
> ```

改为插件的方式使用了。。
